// Platform_Avalon.v

// Generated using ACDS version 25.1 1129

`timescale 1 ps / 1 ps
module Platform_Avalon (
		input  wire        clk_clk,                 //       clk.clk
		output wire        master_waitrequest,      //    master.waitrequest
		output wire [31:0] master_readdata,         //          .readdata
		output wire        master_readdatavalid,    //          .readdatavalid
		input  wire [0:0]  master_burstcount,       //          .burstcount
		input  wire [31:0] master_writedata,        //          .writedata
		input  wire [29:0] master_address,          //          .address
		input  wire        master_write,            //          .write
		input  wire        master_read,             //          .read
		input  wire [3:0]  master_byteenable,       //          .byteenable
		input  wire        master_debugaccess,      //          .debugaccess
		input  wire        registers_waitrequest,   // registers.waitrequest
		input  wire [31:0] registers_readdata,      //          .readdata
		input  wire        registers_readdatavalid, //          .readdatavalid
		output wire [0:0]  registers_burstcount,    //          .burstcount
		output wire [31:0] registers_writedata,     //          .writedata
		output wire [7:0]  registers_address,       //          .address
		output wire        registers_write,         //          .write
		output wire        registers_read,          //          .read
		output wire [3:0]  registers_byteenable,    //          .byteenable
		output wire        registers_debugaccess,   //          .debugaccess
		input  wire        reset_reset_n,           //     reset.reset_n
		input  wire        sdram_waitrequest,       //     sdram.waitrequest
		input  wire [15:0] sdram_readdata,          //          .readdata
		input  wire        sdram_readdatavalid,     //          .readdatavalid
		output wire [0:0]  sdram_burstcount,        //          .burstcount
		output wire [15:0] sdram_writedata,         //          .writedata
		output wire [24:0] sdram_address,           //          .address
		output wire        sdram_write,             //          .write
		output wire        sdram_read,              //          .read
		output wire [1:0]  sdram_byteenable,        //          .byteenable
		output wire        sdram_debugaccess        //          .debugaccess
	);

	wire         master_m0_waitrequest;                        // mm_interconnect_0:master_m0_waitrequest -> master:m0_waitrequest
	wire  [31:0] master_m0_readdata;                           // mm_interconnect_0:master_m0_readdata -> master:m0_readdata
	wire         master_m0_debugaccess;                        // master:m0_debugaccess -> mm_interconnect_0:master_m0_debugaccess
	wire  [29:0] master_m0_address;                            // master:m0_address -> mm_interconnect_0:master_m0_address
	wire         master_m0_read;                               // master:m0_read -> mm_interconnect_0:master_m0_read
	wire   [3:0] master_m0_byteenable;                         // master:m0_byteenable -> mm_interconnect_0:master_m0_byteenable
	wire         master_m0_readdatavalid;                      // mm_interconnect_0:master_m0_readdatavalid -> master:m0_readdatavalid
	wire  [31:0] master_m0_writedata;                          // master:m0_writedata -> mm_interconnect_0:master_m0_writedata
	wire         master_m0_write;                              // master:m0_write -> mm_interconnect_0:master_m0_write
	wire   [0:0] master_m0_burstcount;                         // master:m0_burstcount -> mm_interconnect_0:master_m0_burstcount
	wire  [31:0] jtag_master_readdata;                         // mm_interconnect_0:JTAG_master_readdata -> JTAG:master_readdata
	wire         jtag_master_waitrequest;                      // mm_interconnect_0:JTAG_master_waitrequest -> JTAG:master_waitrequest
	wire  [31:0] jtag_master_address;                          // JTAG:master_address -> mm_interconnect_0:JTAG_master_address
	wire         jtag_master_read;                             // JTAG:master_read -> mm_interconnect_0:JTAG_master_read
	wire   [3:0] jtag_master_byteenable;                       // JTAG:master_byteenable -> mm_interconnect_0:JTAG_master_byteenable
	wire         jtag_master_readdatavalid;                    // mm_interconnect_0:JTAG_master_readdatavalid -> JTAG:master_readdatavalid
	wire         jtag_master_write;                            // JTAG:master_write -> mm_interconnect_0:JTAG_master_write
	wire  [31:0] jtag_master_writedata;                        // JTAG:master_writedata -> mm_interconnect_0:JTAG_master_writedata
	wire  [15:0] mm_interconnect_0_sdram_s0_readdata;          // SDRAM:s0_readdata -> mm_interconnect_0:SDRAM_s0_readdata
	wire         mm_interconnect_0_sdram_s0_waitrequest;       // SDRAM:s0_waitrequest -> mm_interconnect_0:SDRAM_s0_waitrequest
	wire         mm_interconnect_0_sdram_s0_debugaccess;       // mm_interconnect_0:SDRAM_s0_debugaccess -> SDRAM:s0_debugaccess
	wire  [24:0] mm_interconnect_0_sdram_s0_address;           // mm_interconnect_0:SDRAM_s0_address -> SDRAM:s0_address
	wire         mm_interconnect_0_sdram_s0_read;              // mm_interconnect_0:SDRAM_s0_read -> SDRAM:s0_read
	wire   [1:0] mm_interconnect_0_sdram_s0_byteenable;        // mm_interconnect_0:SDRAM_s0_byteenable -> SDRAM:s0_byteenable
	wire         mm_interconnect_0_sdram_s0_readdatavalid;     // SDRAM:s0_readdatavalid -> mm_interconnect_0:SDRAM_s0_readdatavalid
	wire         mm_interconnect_0_sdram_s0_write;             // mm_interconnect_0:SDRAM_s0_write -> SDRAM:s0_write
	wire  [15:0] mm_interconnect_0_sdram_s0_writedata;         // mm_interconnect_0:SDRAM_s0_writedata -> SDRAM:s0_writedata
	wire   [0:0] mm_interconnect_0_sdram_s0_burstcount;        // mm_interconnect_0:SDRAM_s0_burstcount -> SDRAM:s0_burstcount
	wire  [31:0] mm_interconnect_0_registers_s0_readdata;      // Registers:s0_readdata -> mm_interconnect_0:Registers_s0_readdata
	wire         mm_interconnect_0_registers_s0_waitrequest;   // Registers:s0_waitrequest -> mm_interconnect_0:Registers_s0_waitrequest
	wire         mm_interconnect_0_registers_s0_debugaccess;   // mm_interconnect_0:Registers_s0_debugaccess -> Registers:s0_debugaccess
	wire   [7:0] mm_interconnect_0_registers_s0_address;       // mm_interconnect_0:Registers_s0_address -> Registers:s0_address
	wire         mm_interconnect_0_registers_s0_read;          // mm_interconnect_0:Registers_s0_read -> Registers:s0_read
	wire   [3:0] mm_interconnect_0_registers_s0_byteenable;    // mm_interconnect_0:Registers_s0_byteenable -> Registers:s0_byteenable
	wire         mm_interconnect_0_registers_s0_readdatavalid; // Registers:s0_readdatavalid -> mm_interconnect_0:Registers_s0_readdatavalid
	wire         mm_interconnect_0_registers_s0_write;         // mm_interconnect_0:Registers_s0_write -> Registers:s0_write
	wire  [31:0] mm_interconnect_0_registers_s0_writedata;     // mm_interconnect_0:Registers_s0_writedata -> Registers:s0_writedata
	wire   [0:0] mm_interconnect_0_registers_s0_burstcount;    // mm_interconnect_0:Registers_s0_burstcount -> Registers:s0_burstcount
	wire         mm_interconnect_0_ram_on_chip_s1_chipselect;  // mm_interconnect_0:RAM_On_Chip_s1_chipselect -> RAM_On_Chip:chipselect
	wire  [15:0] mm_interconnect_0_ram_on_chip_s1_readdata;    // RAM_On_Chip:readdata -> mm_interconnect_0:RAM_On_Chip_s1_readdata
	wire  [14:0] mm_interconnect_0_ram_on_chip_s1_address;     // mm_interconnect_0:RAM_On_Chip_s1_address -> RAM_On_Chip:address
	wire   [1:0] mm_interconnect_0_ram_on_chip_s1_byteenable;  // mm_interconnect_0:RAM_On_Chip_s1_byteenable -> RAM_On_Chip:byteenable
	wire         mm_interconnect_0_ram_on_chip_s1_write;       // mm_interconnect_0:RAM_On_Chip_s1_write -> RAM_On_Chip:write
	wire  [15:0] mm_interconnect_0_ram_on_chip_s1_writedata;   // mm_interconnect_0:RAM_On_Chip_s1_writedata -> RAM_On_Chip:writedata
	wire         mm_interconnect_0_ram_on_chip_s1_clken;       // mm_interconnect_0:RAM_On_Chip_s1_clken -> RAM_On_Chip:clken
	wire         rst_controller_reset_out_reset;               // rst_controller:reset_out -> [RAM_On_Chip:reset, Registers:reset, SDRAM:reset, master:reset, mm_interconnect_0:JTAG_clk_reset_reset_bridge_in_reset_reset, mm_interconnect_0:master_reset_reset_bridge_in_reset_reset, rst_translator:in_reset]
	wire         rst_controller_reset_out_reset_req;           // rst_controller:reset_req -> [RAM_On_Chip:reset_req, rst_translator:reset_req_in]

	Platform_Avalon_JTAG #(
		.USE_PLI     (0),
		.PLI_PORT    (50000),
		.FIFO_DEPTHS (2)
	) jtag (
		.clk_clk              (clk_clk),                   //          clk.clk
		.clk_reset_reset      (~reset_reset_n),            //    clk_reset.reset
		.master_address       (jtag_master_address),       //       master.address
		.master_readdata      (jtag_master_readdata),      //             .readdata
		.master_read          (jtag_master_read),          //             .read
		.master_write         (jtag_master_write),         //             .write
		.master_writedata     (jtag_master_writedata),     //             .writedata
		.master_waitrequest   (jtag_master_waitrequest),   //             .waitrequest
		.master_readdatavalid (jtag_master_readdatavalid), //             .readdatavalid
		.master_byteenable    (jtag_master_byteenable),    //             .byteenable
		.master_reset_reset   ()                           // master_reset.reset
	);

	Platform_Avalon_RAM_On_Chip ram_on_chip (
		.clk        (clk_clk),                                     //   clk1.clk
		.address    (mm_interconnect_0_ram_on_chip_s1_address),    //     s1.address
		.clken      (mm_interconnect_0_ram_on_chip_s1_clken),      //       .clken
		.chipselect (mm_interconnect_0_ram_on_chip_s1_chipselect), //       .chipselect
		.write      (mm_interconnect_0_ram_on_chip_s1_write),      //       .write
		.readdata   (mm_interconnect_0_ram_on_chip_s1_readdata),   //       .readdata
		.writedata  (mm_interconnect_0_ram_on_chip_s1_writedata),  //       .writedata
		.byteenable (mm_interconnect_0_ram_on_chip_s1_byteenable), //       .byteenable
		.reset      (rst_controller_reset_out_reset),              // reset1.reset
		.reset_req  (rst_controller_reset_out_reset_req),          //       .reset_req
		.freeze     (1'b0)                                         // (terminated)
	);

	altera_avalon_mm_bridge #(
		.DATA_WIDTH        (32),
		.SYMBOL_WIDTH      (8),
		.HDL_ADDR_WIDTH    (8),
		.BURSTCOUNT_WIDTH  (1),
		.PIPELINE_COMMAND  (1),
		.PIPELINE_RESPONSE (1)
	) registers (
		.clk              (clk_clk),                                      //   clk.clk
		.reset            (rst_controller_reset_out_reset),               // reset.reset
		.s0_waitrequest   (mm_interconnect_0_registers_s0_waitrequest),   //    s0.waitrequest
		.s0_readdata      (mm_interconnect_0_registers_s0_readdata),      //      .readdata
		.s0_readdatavalid (mm_interconnect_0_registers_s0_readdatavalid), //      .readdatavalid
		.s0_burstcount    (mm_interconnect_0_registers_s0_burstcount),    //      .burstcount
		.s0_writedata     (mm_interconnect_0_registers_s0_writedata),     //      .writedata
		.s0_address       (mm_interconnect_0_registers_s0_address),       //      .address
		.s0_write         (mm_interconnect_0_registers_s0_write),         //      .write
		.s0_read          (mm_interconnect_0_registers_s0_read),          //      .read
		.s0_byteenable    (mm_interconnect_0_registers_s0_byteenable),    //      .byteenable
		.s0_debugaccess   (mm_interconnect_0_registers_s0_debugaccess),   //      .debugaccess
		.m0_waitrequest   (registers_waitrequest),                        //    m0.waitrequest
		.m0_readdata      (registers_readdata),                           //      .readdata
		.m0_readdatavalid (registers_readdatavalid),                      //      .readdatavalid
		.m0_burstcount    (registers_burstcount),                         //      .burstcount
		.m0_writedata     (registers_writedata),                          //      .writedata
		.m0_address       (registers_address),                            //      .address
		.m0_write         (registers_write),                              //      .write
		.m0_read          (registers_read),                               //      .read
		.m0_byteenable    (registers_byteenable),                         //      .byteenable
		.m0_debugaccess   (registers_debugaccess),                        //      .debugaccess
		.s0_response      (),                                             // (terminated)
		.m0_response      (2'b00)                                         // (terminated)
	);

	altera_avalon_mm_bridge #(
		.DATA_WIDTH        (16),
		.SYMBOL_WIDTH      (8),
		.HDL_ADDR_WIDTH    (25),
		.BURSTCOUNT_WIDTH  (1),
		.PIPELINE_COMMAND  (1),
		.PIPELINE_RESPONSE (1)
	) sdram (
		.clk              (clk_clk),                                  //   clk.clk
		.reset            (rst_controller_reset_out_reset),           // reset.reset
		.s0_waitrequest   (mm_interconnect_0_sdram_s0_waitrequest),   //    s0.waitrequest
		.s0_readdata      (mm_interconnect_0_sdram_s0_readdata),      //      .readdata
		.s0_readdatavalid (mm_interconnect_0_sdram_s0_readdatavalid), //      .readdatavalid
		.s0_burstcount    (mm_interconnect_0_sdram_s0_burstcount),    //      .burstcount
		.s0_writedata     (mm_interconnect_0_sdram_s0_writedata),     //      .writedata
		.s0_address       (mm_interconnect_0_sdram_s0_address),       //      .address
		.s0_write         (mm_interconnect_0_sdram_s0_write),         //      .write
		.s0_read          (mm_interconnect_0_sdram_s0_read),          //      .read
		.s0_byteenable    (mm_interconnect_0_sdram_s0_byteenable),    //      .byteenable
		.s0_debugaccess   (mm_interconnect_0_sdram_s0_debugaccess),   //      .debugaccess
		.m0_waitrequest   (sdram_waitrequest),                        //    m0.waitrequest
		.m0_readdata      (sdram_readdata),                           //      .readdata
		.m0_readdatavalid (sdram_readdatavalid),                      //      .readdatavalid
		.m0_burstcount    (sdram_burstcount),                         //      .burstcount
		.m0_writedata     (sdram_writedata),                          //      .writedata
		.m0_address       (sdram_address),                            //      .address
		.m0_write         (sdram_write),                              //      .write
		.m0_read          (sdram_read),                               //      .read
		.m0_byteenable    (sdram_byteenable),                         //      .byteenable
		.m0_debugaccess   (sdram_debugaccess),                        //      .debugaccess
		.s0_response      (),                                         // (terminated)
		.m0_response      (2'b00)                                     // (terminated)
	);

	altera_avalon_mm_bridge #(
		.DATA_WIDTH        (32),
		.SYMBOL_WIDTH      (8),
		.HDL_ADDR_WIDTH    (30),
		.BURSTCOUNT_WIDTH  (1),
		.PIPELINE_COMMAND  (1),
		.PIPELINE_RESPONSE (1)
	) master (
		.clk              (clk_clk),                        //   clk.clk
		.reset            (rst_controller_reset_out_reset), // reset.reset
		.s0_waitrequest   (master_waitrequest),             //    s0.waitrequest
		.s0_readdata      (master_readdata),                //      .readdata
		.s0_readdatavalid (master_readdatavalid),           //      .readdatavalid
		.s0_burstcount    (master_burstcount),              //      .burstcount
		.s0_writedata     (master_writedata),               //      .writedata
		.s0_address       (master_address),                 //      .address
		.s0_write         (master_write),                   //      .write
		.s0_read          (master_read),                    //      .read
		.s0_byteenable    (master_byteenable),              //      .byteenable
		.s0_debugaccess   (master_debugaccess),             //      .debugaccess
		.m0_waitrequest   (master_m0_waitrequest),          //    m0.waitrequest
		.m0_readdata      (master_m0_readdata),             //      .readdata
		.m0_readdatavalid (master_m0_readdatavalid),        //      .readdatavalid
		.m0_burstcount    (master_m0_burstcount),           //      .burstcount
		.m0_writedata     (master_m0_writedata),            //      .writedata
		.m0_address       (master_m0_address),              //      .address
		.m0_write         (master_m0_write),                //      .write
		.m0_read          (master_m0_read),                 //      .read
		.m0_byteenable    (master_m0_byteenable),           //      .byteenable
		.m0_debugaccess   (master_m0_debugaccess),          //      .debugaccess
		.s0_response      (),                               // (terminated)
		.m0_response      (2'b00)                           // (terminated)
	);

	Platform_Avalon_mm_interconnect_0 mm_interconnect_0 (
		.clk_0_clk_clk                              (clk_clk),                                      //                            clk_0_clk.clk
		.JTAG_clk_reset_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),               // JTAG_clk_reset_reset_bridge_in_reset.reset
		.master_reset_reset_bridge_in_reset_reset   (rst_controller_reset_out_reset),               //   master_reset_reset_bridge_in_reset.reset
		.JTAG_master_address                        (jtag_master_address),                          //                          JTAG_master.address
		.JTAG_master_waitrequest                    (jtag_master_waitrequest),                      //                                     .waitrequest
		.JTAG_master_byteenable                     (jtag_master_byteenable),                       //                                     .byteenable
		.JTAG_master_read                           (jtag_master_read),                             //                                     .read
		.JTAG_master_readdata                       (jtag_master_readdata),                         //                                     .readdata
		.JTAG_master_readdatavalid                  (jtag_master_readdatavalid),                    //                                     .readdatavalid
		.JTAG_master_write                          (jtag_master_write),                            //                                     .write
		.JTAG_master_writedata                      (jtag_master_writedata),                        //                                     .writedata
		.master_m0_address                          (master_m0_address),                            //                            master_m0.address
		.master_m0_waitrequest                      (master_m0_waitrequest),                        //                                     .waitrequest
		.master_m0_burstcount                       (master_m0_burstcount),                         //                                     .burstcount
		.master_m0_byteenable                       (master_m0_byteenable),                         //                                     .byteenable
		.master_m0_read                             (master_m0_read),                               //                                     .read
		.master_m0_readdata                         (master_m0_readdata),                           //                                     .readdata
		.master_m0_readdatavalid                    (master_m0_readdatavalid),                      //                                     .readdatavalid
		.master_m0_write                            (master_m0_write),                              //                                     .write
		.master_m0_writedata                        (master_m0_writedata),                          //                                     .writedata
		.master_m0_debugaccess                      (master_m0_debugaccess),                        //                                     .debugaccess
		.RAM_On_Chip_s1_address                     (mm_interconnect_0_ram_on_chip_s1_address),     //                       RAM_On_Chip_s1.address
		.RAM_On_Chip_s1_write                       (mm_interconnect_0_ram_on_chip_s1_write),       //                                     .write
		.RAM_On_Chip_s1_readdata                    (mm_interconnect_0_ram_on_chip_s1_readdata),    //                                     .readdata
		.RAM_On_Chip_s1_writedata                   (mm_interconnect_0_ram_on_chip_s1_writedata),   //                                     .writedata
		.RAM_On_Chip_s1_byteenable                  (mm_interconnect_0_ram_on_chip_s1_byteenable),  //                                     .byteenable
		.RAM_On_Chip_s1_chipselect                  (mm_interconnect_0_ram_on_chip_s1_chipselect),  //                                     .chipselect
		.RAM_On_Chip_s1_clken                       (mm_interconnect_0_ram_on_chip_s1_clken),       //                                     .clken
		.Registers_s0_address                       (mm_interconnect_0_registers_s0_address),       //                         Registers_s0.address
		.Registers_s0_write                         (mm_interconnect_0_registers_s0_write),         //                                     .write
		.Registers_s0_read                          (mm_interconnect_0_registers_s0_read),          //                                     .read
		.Registers_s0_readdata                      (mm_interconnect_0_registers_s0_readdata),      //                                     .readdata
		.Registers_s0_writedata                     (mm_interconnect_0_registers_s0_writedata),     //                                     .writedata
		.Registers_s0_burstcount                    (mm_interconnect_0_registers_s0_burstcount),    //                                     .burstcount
		.Registers_s0_byteenable                    (mm_interconnect_0_registers_s0_byteenable),    //                                     .byteenable
		.Registers_s0_readdatavalid                 (mm_interconnect_0_registers_s0_readdatavalid), //                                     .readdatavalid
		.Registers_s0_waitrequest                   (mm_interconnect_0_registers_s0_waitrequest),   //                                     .waitrequest
		.Registers_s0_debugaccess                   (mm_interconnect_0_registers_s0_debugaccess),   //                                     .debugaccess
		.SDRAM_s0_address                           (mm_interconnect_0_sdram_s0_address),           //                             SDRAM_s0.address
		.SDRAM_s0_write                             (mm_interconnect_0_sdram_s0_write),             //                                     .write
		.SDRAM_s0_read                              (mm_interconnect_0_sdram_s0_read),              //                                     .read
		.SDRAM_s0_readdata                          (mm_interconnect_0_sdram_s0_readdata),          //                                     .readdata
		.SDRAM_s0_writedata                         (mm_interconnect_0_sdram_s0_writedata),         //                                     .writedata
		.SDRAM_s0_burstcount                        (mm_interconnect_0_sdram_s0_burstcount),        //                                     .burstcount
		.SDRAM_s0_byteenable                        (mm_interconnect_0_sdram_s0_byteenable),        //                                     .byteenable
		.SDRAM_s0_readdatavalid                     (mm_interconnect_0_sdram_s0_readdatavalid),     //                                     .readdatavalid
		.SDRAM_s0_waitrequest                       (mm_interconnect_0_sdram_s0_waitrequest),       //                                     .waitrequest
		.SDRAM_s0_debugaccess                       (mm_interconnect_0_sdram_s0_debugaccess)        //                                     .debugaccess
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~reset_reset_n),                     // reset_in0.reset
		.clk            (clk_clk),                            //       clk.clk
		.reset_out      (rst_controller_reset_out_reset),     // reset_out.reset
		.reset_req      (rst_controller_reset_out_reset_req), //          .reset_req
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_in1      (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

endmodule
